version: '3'
services:
  rstudio:
    container_name: rstudio
    image: rocker/tidyverse:latest
    ports:
      - 8787:8787
    volumes:
      - /public_projects:/home/rstudio/public_projects
      - /private_projects:/home/rstudio/private_projects
    env_file:
      - /secrets/rstudio/creds.env
  jenkins:
    container_name: jenkins
    build: jenkins
    image: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - /secrets/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
  shinyproxy:
    container_name: shinyproxy
    build: shinyproxy
    image: shinyproxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: shinyproxy-net