version: '3'
services:
# Proxy to forward https connections to shinyproxy and rstudio
  nginx_proxy:
    container_name: nginx_proxy
    image: nginx_proxy
    build: containers/nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./secrets/nginx_proxy:/etc/ssl/
    restart: always
# Rstudio server
  rstudio:
    container_name: rstudio
    image: rocker/tidyverse:latest
    ports:
      - 8888:8787
    volumes:
      - ./public_projects:/home/rstudio/public_projects
      - ./private_projects:/home/rstudio/private_projects
      - ./scripts:/home/rstudio/scripts
    env_file:
      - ./secrets/rstudio/creds.env
    restart: always
# Jenkins handles automated builds
  jenkins:
    container_name: jenkins
    build: containers/jenkins
    image: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./secrets/jenkins:/var/jenkins_home
      - ../personal-server:/var/personal-server
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
# Launch shinyproxy for managing shiny apps
  shinyproxy:
    container_name: shinyproxy
    build: containers/shinyproxy
    image: shinyproxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
# Watchtower is a process for watching your Docker containers and automatically
# updating and restarting them whenever their base image is refreshed.
  watchtower:
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    # Look for new images every hour and removes old images
    # Removing --no-pull will allow watchtower to get images from repos (will not work for built images)
    command: --schedule "0 0 * *" --cleanup --no-pull
networks:
  default:
    external:
      name: server-net
