version: '3'
services:
  nginx_proxy:
    container_name: nginx_proxy
    image: nginx_proxy
    build: containers/nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./secrets/nginx_proxy:/etc/ssl/
    restart: always
  rstudio:
    container_name: rstudio
    image: rocker/tidyverse:latest
    ports:
      - 8888:8787
    volumes:
      - ./public_projects:/home/rstudio/public_projects
      - ./private_projects:/home/rstudio/private_projects
      - ./scripts:/home/rstudio/scripts
    env_file:
      - ./secrets/rstudio/creds.env
    restart: always
  jenkins:
    container_name: jenkins
    build: containers/jenkins
    image: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./secrets/jenkins:/var/jenkins_home
      - ../personal-server:/opt/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  shinyproxy:
    container_name: shinyproxy
    build: containers/shinyproxy
    image: shinyproxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  default:
    external:
      name: shinyproxy-net
