
version: '3'
services:
  rstudio:
    container_name: rstudio
    image: rocker/tidyverse:latest
    ports:
      - 8787:8787
    volumes:
      - ../public_projects:/home/rstudio/public_projects
      - ../private_projects:/home/rstudio/private_projects
    env_file:
      - ../secrets/rstudio/creds.env
  shinyproxy:
    container_name: shinyproxy
    build: shinyproxy
    image: shinyproxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  exploreidmodels:
    container_name: exploreidmodels
    image: seabbs/exploreidmodels:latest
    command: ["Rscript", "-e", "shiny::runApp('/home/rstudio/exploreidmodels', port = 3838, host = '0.0.0.0', display.mode = 'normal')"]
    ports:
      - 3838:3838
  intro_to_tb_models:
    container_name: intro_to_tb_models
    image: seabbs/intro_to_tb_models:latest
    ports:
      - 3839:3838
  fcdashboard:
    container_name: fcdashboard
    image: seabbs/fcdashboard:latest
    ports:
      - 3840:3838
    volumes:
      - ../secrets/fcdashboard/loanbook.csv:/home/fcdashboard/loanbook.csv
  thepebblegame:
    container_name: thepebblegame
    image: seabbs/thepebblegame:latest
    ports:
      - 3841:3838
  showmeperseus:
    container_name: showmeperseus
    image: seabbs/showmeperseus:latest
    command: ["Rscript", "-e", "rmarkdown::run('/home/rstudio/ShowMePerseus/index.Rmd', shiny_args = list(port = 3838, host = '0.0.0.0'))"]
    ports:
      - 3842:3838
  tb_england_wales:
    container_name: tb_england_wales
    image: seabbs/tb_england_wales:latest
    command: ["Rscript", "-e", "rmarkdown::run('/home/rstudio/TB_England_Wales/index.Rmd', shiny_args = list(port = 3838, host = '0.0.0.0'))"]
    ports:
      - 3843:3838
  exploreglobaltb:
    container_name: exploreglobaltb
    image: seabbs/gettbinr:latest
    command: ["Rscript", "-e", "shiny::runApp('/home/rstudio/getTBinR/inst/shiny/ExploreGlobalTB', port = 3838, host = '0.0.0.0')"]
    ports:
      - 3844:3838
networks:
  default:
    external:
      name: shinyproxy-net