
version: '3'
services:
  shinyproxy:
    container_name: shinyproxy
    build: shinyproxy
    networks: 
      - docker-shinyproxy-net
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  exploreidmodels:
    image: seabbs/exploreidmodels:latest
    command: ["Rscript", "-e", "shiny::runApp('/home/rstudio/exploreidmodels', port = 3838, host = '0.0.0.0')"]
    ports:
      - 3838:3838
  intro_to_tb_models:
    image: seabbs/intro_to_tb_models:latest
    ports:
      - 3838:3838
  fcdashboard:
    image: seabbs/fcdashboard:latest
    ports:
      - 3838:3838
    volumes:
      - /personal-server/secrets/fcdashboard:/home/rstudio/fcdashboard