
version: '3'
services:
  ## Scheduled Scripts
  h2o_tweets:
    container_name: h2o_tweets
    image: seabbs/h2o_tweets:latest
    volumes:
      - ../secrets/h2o_tweets:/home/h2o_tweets/auth
      - ../scripts/bin:/home/h2o_tweets/bin
    command: ["bash", "bin/run_h2o_bot.sh"]
  tweetrstudiocheatsheets:
    container_name: tweetrstudiocheatsheets
    image: seabbs/tweetrstudiocheatsheets:latest
    volumes:
      - ../secrets/tweetrstudiocheatsheets:/home/TweetRstudioCheatsheets/storage
    command: ["Rscript", "bot.R"]
  ## Applications
  exploreidmodels:
    container_name: exploreidmodels
    image: exploreidmodels
    build: exploreidmodels
    ports:
      - 3838:3838
  intro_to_tb_models:
    container_name: intro_to_tb_models
    image: seabbs/intro_to_tb_models:latest
    ports:
      - 3839:3838
  fcdashboard:
    container_name: fcdashboard
    image: seabbs/fcdashboard:latest
    ports:
      - 3840:3838
    volumes:
      - ../secrets/fcdashboard:/home/fcdashboard/storage/
  thepebblegame:
    container_name: thepebblegame
    image: seabbs/thepebblegame:latest
    ports:
      - 3841:3838
  showmeperseus:
    container_name: showmeperseus
    build: showmeperseus
    image: showmeperseus
    ports:
      - 3842:3838
  tb_england_wales:
    container_name: tb_england_wales
    image: tb_england_wales
    build: tb_england_wales
    ports:
      - 3843:3838
  exploreglobaltb:
    container_name: exploreglobaltb
    build: exploreglobaltb
    image: exploreglobaltb
    ports:
      - 3844:3838
networks:
  default:
    external:
      name: shinyproxy-net
