
version: '3'
services:
  nginx_proxy:
    image: nginx_proxy
    build: nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../secrets/nginx_proxy:/etc/ssl/
  rstudio:
    container_name: rstudio
    image: rocker/tidyverse:latest
    ports:
      - 8888:8787
    volumes:
      - ../public_projects:/home/rstudio/public_projects
      - ../private_projects:/home/rstudio/private_projects
      - ../scripts:/home/rstudio/scripts
    env_file:
      - ../secrets/rstudio/creds.env
  jenkins:
    container_name: jenkins
    build: jenkins
    image: jenkins
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ../secrets/jenkins:/var/jenkins_home
      - ../../personal-server:/var/personal-server
      - /var/run/docker.sock:/var/run/docker.sock
  h2o_tweets:
    container_name: h2o_tweets
    image: seabbs/h2o_tweets:latest
    volumes:
      - ../secrets/h2o_tweets:/home/auth
    command: ["bash ../auth/run.sh"]
  tweetrstudiocheatsheets:
    container_name: tweetrstudiocheatsheets
    image: seabbs/tweetrstudiocheatsheets:latest
    volumes:
      - ../secrets/tweetrstudiocheatsheets:/home/TweetRstudioCheatsheets/storage
    command: ["Rscript", "bot.R"]
  shinyproxy:
    container_name: shinyproxy
    build: shinyproxy
    image: shinyproxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../secrets/nginx_proxy:/home/samabbott/
  exploreidmodels:
    container_name: exploreidmodels
    image: exploreidmodels
    build: exploreidmodels
    ports:
      - 3838:3838
  intro_to_tb_models:
    container_name: intro_to_tb_models
    image: seabbs/intro_to_tb_models:latest
    ports:
      - 3839:3838
  fcdashboard:
    container_name: fcdashboard
    image: seabbs/fcdashboard:latest
    ports:
      - 3840:3838
    volumes:
      - ../secrets/fcdashboard:/home/fcdashboard/storage/
  thepebblegame:
    container_name: thepebblegame
    image: seabbs/thepebblegame:latest
    ports:
      - 3841:3838
  showmeperseus:
    container_name: showmeperseus
    build: showmeperseus
    image: showmeperseus
    ports:
      - 3842:3838
  tb_england_wales:
    container_name: tb_england_wales
    image: tb_england_wales
    build: tb_england_wales
    ports:
      - 3843:3838
  exploreglobaltb:
    container_name: exploreglobaltb
    build: exploreglobaltb
    image: exploreglobaltb
    ports:
      - 3844:3838
networks:
  default:
    external:
      name: shinyproxy-net
