shiny:
  proxy:
    title: Sam Abbott's App Server
    logo-url: https://raw.githubusercontent.com/seabbs/seabbs.github.io/sources/static/img/portrait.jpg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: none
    container-backend: kubernetes
    kubernetes:
      internal-networking: true
      url: http://localhost:8001
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo

logging:
  file:
    shinyproxy.log
